version: '2.2'
volumes:
  nvidia_driver_384.59:
    external:
      name: nvidia_driver_384.59
services:
  gpu-miner:
    build: .
    image: valentinvieriu/docker-xmr-stack-gpu:v1.1.1-1.4.0
    container_name: xmr-gpu-miner
    # cpuset: 0,1
    # cpus: 6
    stdin_open: true
    environment:
      WALLET_ADDRESS: ${WALLET_ADDRESS}.gpu0
      POOL_ADDRESS: ${POOL_ADDRESS}
      POOL_PASSWORD: ${POOL_PASSWORD}
      GPU_THREADS: 65
      GPU_BLOCKS: 60
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    devices: 
      - '/dev/nvidia0:/dev/nvidia0'
      - '/dev/nvidiactl:/dev/nvidiactl'
      - '/dev/nvidia-uvm:/dev/nvidia-uvm'
      - '/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools'
    # entrypoint: "/bin/bash -c"
    volumes:
      - 'nvidia_driver_384.59:/usr/local/nvidia:ro'